-- MySQL Script generated by MySQL Workbench
-- Fri Aug 31 13:03:12 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema AplicacionBD
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema AplicacionBD
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `AplicacionBD` DEFAULT CHARACTER SET utf8 ;
USE `AplicacionBD` ;

-- -----------------------------------------------------
-- Table `AplicacionBD`.`Red_Bibliotecas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AplicacionBD`.`Red_Bibliotecas` (
  `CODIGO_DANE` VARCHAR(100) NOT NULL,
  `DEPARTAMENTO` VARCHAR(100) NOT NULL,
  `MUNICIPIO` VARCHAR(100) NOT NULL,
  `CENTRO_POBLADO` VARCHAR(100) NOT NULL,
  `NATURALEZA_BIBLIOTECA` VARCHAR(100) NOT NULL,
  `TIPO_BIBLIOTECA` VARCHAR(100) NOT NULL,
  `NOMBRE_BIBLIOTECA` VARCHAR(100) NOT NULL,
  `DIRECCION_BIBLIOTECA` VARCHAR(100) NOT NULL,
  `BARRIO` VARCHAR(100) NOT NULL,
  `TELEFONO` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`CODIGO_DANE`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
